/**
 * @file
 * Handles responsive navigation blocks (breadcrumbs and tabs).
 */
(function ($, Drupal) {

  'use strict';

  function init(i, breadcrumb_block) {
    var $bcBlock = $(breadcrumb_block);
    var $tabsBlock = $bcBlock.siblings('.block-local-tasks-block');

    function handleResize() {
      $tabsBlock.addClass('is-combined-with-breadcrumb');

      var breadcrumbWidth = 0;
      $bcBlock.find('ol > li').each(function (index, elem) {
        breadcrumbWidth += $(elem).outerWidth(true);
      });

      var primaryTabsWidth = 0;
      $tabsBlock.find('.tabs.primary > li').each(function (index, elem) {
        primaryTabsWidth += $(elem).outerWidth(true);
      });

      $tabsBlock.toggleClass('is-combined-with-breadcrumb', $bcBlock.innerWidth() > (breadcrumbWidth + primaryTabsWidth));
    }

    $(window).on('resize.tabs', Drupal.debounce(handleResize, 50)).trigger('resize.tabs');

    // Register triggering of resize on menu expand.
    $('[data-toolbar-tray="toolbar-item-administration-tray"]')
      .once('responsive-navigation')
      .on('click', function () {
        $(window).trigger('resize.tabs');
      });
  }

  /**
   * Initialise the navigation JS.
   */
  Drupal.behaviors.navigation = {
    attach: function (context) {
      var $bcBlock = $(context).find('.block-system-breadcrumb-block');
      if ($bcBlock.length) {
        var notSmartPhone = window.matchMedia('(min-width: 300px)');
        if (notSmartPhone.matches) {
          $bcBlock.once('responsive-navigation').each(init);
        }
      }
    }
  };

})(jQuery, Drupal);
;
/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function ($, Drupal) {
  function init(i, tab) {
    var $tab = $(tab);
    var $target = $tab.find('[data-drupal-nav-tabs-target]');
    var isCollapsible = $tab.hasClass('is-collapsible');

    function openMenu(e) {
      $target.toggleClass('is-open');
    }

    function handleResize(e) {
      $tab.addClass('is-horizontal');
      var $tabs = $tab.find('.tabs');
      var isHorizontal = $tabs.outerHeight() <= $tabs.find('.tabs__tab').outerHeight();
      $tab.toggleClass('is-horizontal', isHorizontal);
      if (isCollapsible) {
        $tab.toggleClass('is-collapse-enabled', !isHorizontal);
      }
      if (isHorizontal) {
        $target.removeClass('is-open');
      }
    }

    $tab.addClass('position-container is-horizontal-enabled');

    $tab.on('click.tabs', '[data-drupal-nav-tabs-trigger]', openMenu);
    $(window).on('resize.tabs', Drupal.debounce(handleResize, 150)).trigger('resize.tabs');
  }

  Drupal.behaviors.navTabs = {
    attach: function attach(context, settings) {
      var $tabs = $(context).find('[data-drupal-nav-tabs]');
      if ($tabs.length) {
        var notSmartPhone = window.matchMedia('(min-width: 300px)');
        if (notSmartPhone.matches) {
          $tabs.once('nav-tabs').each(init);
        }
      }
    }
  };
})(jQuery, Drupal);;
